%% find your old code, copy and paste.
function xt = load_sinewave_opponent_stimulus(dir)
which_phase = 1;
% load stimulus parameters and plot from there.
S = GetSystemConfiguration;
stimulus_parameters_file = fullfile(S.sac_parameter_filepath, 'sinewave_opponent.mat');
data = load(stimulus_parameters_file);

stimulus_parameters = data.stimulus_parameters;
epoch_index = find(stimulus_parameters.direction == dir);
epoch_index = epoch_index(1);

sw = stimulus_parameters.spatial_wavelength(epoch_index);
tf =  stimulus_parameters.temporal_frequency(epoch_index);
disp(['counter-phase stimulus demo, spatial frequency = ', num2str(sw), ', temporal frequency = ', num2str(tf)]);

if dir == 0
    xt_pref = make_sinewave(tf,...
        sw, ...
        stimulus_parameters.contrast(epoch_index), ...
        1,...
        stimulus_parameters.phaseVals(epoch_index),...
        sw, ...
        stimulus_parameters.temporal_duration(epoch_index),...
        stimulus_parameters.fps(epoch_index), ...
        stimulus_parameters.pixel_size(epoch_index));
    xt_null = make_sinewave(tf,...
        stimulus_parameters.spatial_wavelength(epoch_index), ...
        stimulus_parameters.contrast(epoch_index), ...
        -1,...
        stimulus_parameters.phaseVals(epoch_index),...
        sw, ...
        stimulus_parameters.temporal_duration(epoch_index),...
        stimulus_parameters.fps(epoch_index), ...
        stimulus_parameters.pixel_size(epoch_index));
    xt = xt_pref + xt_null;
else

    xt = make_sinewave(tf,...
        sw, ...
        stimulus_parameters.contrast(epoch_index), ...
        stimulus_parameters.direction(epoch_index),...
        stimulus_parameters.phaseVals(epoch_index),...
        stimulus_parameters.spatial_range(epoch_index), ...
        stimulus_parameters.temporal_duration(epoch_index),...
        stimulus_parameters.fps(epoch_index), ...
        stimulus_parameters.pixel_size(epoch_index));
end
end

