addpath(genpath("../"))
figure_edge_response()
figure_white_noise()
figure_scintillator()
figure_sinewave()
figure_opponent()
figure_single_bar()
figure_two_simultaneous_bars()
figure_apparent_motion()

