function SAC_Utils_data_base_from_xlsx_to_table()
S = GetSystemConfiguration;
sac_data_file = fullfile(S.sac_data_path, 'stim_info','SAC_calcium_database.xlsx');
opts = detectImportOptions(sac_data_file);
opts.VariableTypes{1} = 'char';

T = readtable(sac_data_file, opts);

stimSet = {'ApparentMotion',...
    'Scintillator', ...
    'Sinewave',...
    'Opponency', ...
    'Scintillator_2019_03_26', ...
    'Opponency_2019_03_26',  ...
    'Sinewave_2019_03_26', ...
    'ApparentMotion_2019_03_26', ...
    'grating_8_direction',...
    'sinewave_sweep_dense'...
    'apparent_motion', ...
    'scintillator',...
    'sinewave_opponent',...
    'edges',...
    'white_noise'};

clarkSet = {'Clark1', 'Clark2','Clark3', 'Clark4', 'Clark5', 'Clark6', 'Clark7', 'Clark8', 'Clark9', 'dense_sinewave','apparent_motion','scintillator', 'sinewave_opponent', 'edges', 'white_noise'};
number = [1,2,3,4,5,6,7,8,9,10,11,12,13, 14, 15];
stim_to_clark = containers.Map(stimSet,clarkSet);
stim_to_number = containers.Map(stimSet,number);
clark_to_stim = containers.Map(clarkSet,number);
manual_select = T.manualSelect;

%
cell_name = cellfun(@(x, y) [x, '_', y], T.file_prefix, T.file_suffix , 'UniformOutput', false);
number = cellfun(@(x) clark_to_stim(x), T.stim);

T_cell_to_stim = table(cell_name, number);

save(fullfile(S.sac_data_path,'stim_info', 'data_base.mat') ,'T_cell_to_stim', 'stim_to_number', 'manual_select');